-- UAVHelpline database schema for Supabase.
-- Run this once in the Supabase dashboard → SQL Editor → New query → Run.

create table if not exists posts (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  status text not null default 'draft',          -- 'draft' | 'published'
  date date,
  category text not null default 'news',
  tags text[] default '{}',
  tldr text,
  meta_description text,
  image text,
  sources text[] default '{}',
  safety_review boolean default false,
  author text default 'UAVHelpline Editorial',
  body text,
  created_at timestamptz default now()
);

create index if not exists posts_status_date_idx on posts (status, date desc);
create index if not exists posts_category_idx on posts (category);

-- Row Level Security: the public can read only published posts.
-- The editor (a logged-in user) can do everything. The server uses the
-- service-role key, which bypasses RLS, so drafts and publishing work server-side.
alter table posts enable row level security;

drop policy if exists "public reads published" on posts;
create policy "public reads published"
  on posts for select
  using (status = 'published');

drop policy if exists "authenticated full access" on posts;
create policy "authenticated full access"
  on posts for all
  to authenticated
  using (true)
  with check (true);

-- Storage bucket for hero images generated by the morning automation.
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;
